language: emacs-lisp
env:
  matrix:
    - EMACS=emacs24
    - EMACS=emacs-snapshot
  global:
    - CASK=$HOME/.cask/bin/cask
before_install:
  - sudo add-apt-repository -y ppa:cassou/emacs
  - sudo add-apt-repository -y ppa:ubuntu-elisp/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq $EMACS
  - if [ "$EMACS" = 'emacs-snapshot' ]; then
      sudo apt-get install -qq emacs-snapshot-el emacs-snapshot-nox;
    fi
  - curl -fsSkL --max-time 10 --retry 10 --retry-delay 10
        https://raw.github.com/cask/cask/master/go | python
script:
  make test
